"""Processing helpers for Sequenced Bake."""

import os

import bpy
import numpy as np


TEMP_NODE_TAG = "__SEQBAKE_TEMP__"


IMAGE_FORMAT_MAP = {
    "PNG": "PNG",
    "JPEG": "JPEG",
    "BMP": "BMP",
    "TIFF": "TIFF",
    "TGA": "TGA",
    "OPENEXR": "OPEN_EXR",
    "EXR": "OPEN_EXR",
    "HDR": "HDR",
    "CINEON": "CINEON",
    "DPX": "DPX",
}


def clear_generated_textures(props, images=None):
    """Remove only images generated by the current bake operation.

    Args:
        props: Sequenced Bake property group.
        images: Optional iterable of images created by the operation.
    """
    if not props.sequence_clear_baked_maps or not images:
        return

    for image in list(images):
        if image is not None:
            try:
                bpy.data.images.remove(image)
            except (ReferenceError, RuntimeError) as exc:
                print(f"[Sequenced Bake] Failed to remove generated image '{getattr(image, 'name', '<unknown>')}': {exc}")


def _find_principled_and_output(material):
    """Return the first Principled BSDF and active Material Output nodes."""
    nodes = material.node_tree.nodes
    bsdf = next((node for node in nodes if node.type == "BSDF_PRINCIPLED"), None)
    output = next(
        (
            node
            for node in nodes
            if node.type == "OUTPUT_MATERIAL" and getattr(node, "is_active_output", False)
        ),
        None,
    )
    if output is None:
        output = next((node for node in nodes if node.type == "OUTPUT_MATERIAL"), None)
    return bsdf, output


def connect_metallic_node(material):
    """Prepare a material for metallic baking and return restoration state.

    The metallic value is routed into an emission shader so the standard
    Cycles EMIT bake produces the scalar metallic signal as RGB.

    Args:
        material: Material whose node tree will be temporarily modified.

    Returns:
        dict: Exact output-surface links and temporary nodes for restoration.

    Raises:
        RuntimeError: If the material does not contain the required nodes.
    """
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf, output = _find_principled_and_output(material)

    if not bsdf or not output:
        raise RuntimeError("Required nodes not found for metallic bake")

    state = {
        "surface_links": [(link.from_socket, link.to_socket) for link in output.inputs["Surface"].links],
        "temporary_nodes": [],
    }

    emission = nodes.new(type="ShaderNodeEmission")
    emission.label = TEMP_NODE_TAG
    emission.inputs["Strength"].default_value = 1.0

    if bsdf.inputs["Metallic"].is_linked:
        links.new(bsdf.inputs["Metallic"].links[0].from_socket, emission.inputs["Color"])
    else:
        value = float(bsdf.inputs["Metallic"].default_value)
        emission.inputs["Color"].default_value = (value, value, value, 1.0)

    for link in list(output.inputs["Surface"].links):
        links.remove(link)
    links.new(emission.outputs["Emission"], output.inputs["Surface"])
    state["temporary_nodes"] = [emission]
    return state


def connect_occlusion_node(material):
    """Prepare an ORM material and return exact restoration state.

    The generated shader emits ambient occlusion, roughness, and metallic
    values as RGB so the result can be baked into a single image.

    Args:
        material: Material whose node tree will be temporarily modified.

    Returns:
        dict: Temporary nodes and original output links.

    Raises:
        RuntimeError: If the material does not contain the required nodes.
    """
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf, output = _find_principled_and_output(material)

    if not bsdf or not output:
        raise RuntimeError("Required nodes not found for occlusion bake")

    state = {
        "surface_links": [(link.from_socket, link.to_socket) for link in output.inputs["Surface"].links],
        "temporary_nodes": [],
    }

    combine = nodes.new(type="ShaderNodeCombineColor")
    combine.mode = "RGB"
    combine.label = TEMP_NODE_TAG

    ao = nodes.new(type="ShaderNodeAmbientOcclusion")
    ao.samples = 16
    ao.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    ao.label = TEMP_NODE_TAG

    temp_bsdf = nodes.new(type="ShaderNodeBsdfPrincipled")
    temp_bsdf.label = TEMP_NODE_TAG
    temp_bsdf.inputs["Base Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    temp_bsdf.inputs["Roughness"].default_value = 1.0
    if "Emission Strength" in temp_bsdf.inputs:
        temp_bsdf.inputs["Emission Strength"].default_value = 1.0

    links.new(ao.outputs["Color"], combine.inputs["Red"])

    if bsdf.inputs["Metallic"].is_linked:
        links.new(bsdf.inputs["Metallic"].links[0].from_socket, combine.inputs["Green"])
    else:
        combine.inputs["Green"].default_value = bsdf.inputs["Metallic"].default_value

    if bsdf.inputs["Roughness"].is_linked:
        links.new(bsdf.inputs["Roughness"].links[0].from_socket, combine.inputs["Blue"])
    else:
        combine.inputs["Blue"].default_value = bsdf.inputs["Roughness"].default_value

    if "Alpha" in bsdf.inputs and "Alpha" in temp_bsdf.inputs:
        if bsdf.inputs["Alpha"].is_linked:
            links.new(bsdf.inputs["Alpha"].links[0].from_socket, temp_bsdf.inputs["Alpha"])
        else:
            temp_bsdf.inputs["Alpha"].default_value = bsdf.inputs["Alpha"].default_value

    if "Normal" in bsdf.inputs and "Normal" in temp_bsdf.inputs:
        if bsdf.inputs["Normal"].is_linked:
            links.new(bsdf.inputs["Normal"].links[0].from_socket, temp_bsdf.inputs["Normal"])

    links.new(combine.outputs["Color"], temp_bsdf.inputs["Emission Color"])

    for link in list(output.inputs["Surface"].links):
        links.remove(link)
    links.new(temp_bsdf.outputs["BSDF"], output.inputs["Surface"])

    state["temporary_nodes"] = [combine, ao, temp_bsdf]
    return state


def restore_material_state(material, state):
    """Restore a material's exact surface links and remove temporary nodes."""
    if not state:
        return

    nodes = material.node_tree.nodes
    links = material.node_tree.links
    _, output = _find_principled_and_output(material)

    if output:
        for link in list(output.inputs["Surface"].links):
            links.remove(link)

        for from_socket, to_socket in state.get("surface_links", []):
            try:
                links.new(from_socket, to_socket)
            except (ReferenceError, RuntimeError) as exc:
                print(f"[Sequenced Bake] Failed to restore material link: {exc}")

    for node in state.get("temporary_nodes", []):
        try:
            if node.name in nodes:
                nodes.remove(node)
        except (ReferenceError, RuntimeError) as exc:
            print(f"[Sequenced Bake] Failed to remove temporary node: {exc}")


def reconnect_node(material, state=None, temp_tag=TEMP_NODE_TAG):
    """Restore temporary material state.

    The state-aware path is preferred. The tag-based path remains available
    for compatibility with older callers.
    """
    if state is not None:
        restore_material_state(material, state)
        return

    nodes = material.node_tree.nodes
    for node in list(nodes):
        if node.label == temp_tag:
            nodes.remove(node)


def calculate_sculpt_bounds(obj):
    """Calculate symmetric object-space bounds for sculpt-map encoding.

    The bounds are based on the evaluated mesh so modifiers are represented.
    Each axis is guaranteed to have a non-zero normalization divisor.

    Args:
        obj: Mesh object to evaluate.

    Returns:
        numpy.ndarray: Three positive axis extents.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    obj_eval = obj.evaluated_get(depsgraph)
    mesh_data = None

    try:
        mesh_data = obj_eval.to_mesh()
        if mesh_data is None or not mesh_data.vertices:
            raise RuntimeError(f"Failed to evaluate mesh for object: {obj.name}")

        coords = np.empty((len(mesh_data.vertices), 3), dtype=np.float32)
        mesh_data.vertices.foreach_get("co", coords.ravel())
        max_abs = np.max(np.abs(coords), axis=0)
        return np.where(max_abs == 0.0, 1.0, max_abs).astype(np.float32)
    finally:
        if mesh_data is not None:
            obj_eval.to_mesh_clear()


def _unwrap_uv_triangle(uvs):
    """Return a UV triangle adjusted across 0/1 seams when necessary."""
    result = np.asarray(uvs, dtype=np.float32).copy()
    base = result[0].copy()

    for index in (1, 2):
        delta = result[index] - base
        result[index] -= np.round(delta)

    return result


def _rasterize_sculpt_triangle(pixels, width, height, uv_triangle, positions, bounds):
    """Rasterize one UV triangle into the sculpt-map pixel buffer."""
    uv = _unwrap_uv_triangle(uv_triangle)
    uv1, uv2, uv3 = uv
    det = (
        (uv2[1] - uv3[1]) * (uv1[0] - uv3[0]) +
        (uv3[0] - uv2[0]) * (uv1[1] - uv3[1])
    )
    if abs(det) < 1e-12:
        return

    # A UV island can cross the 0/1 seam. Rasterize the triangle in each
    # neighboring UV tile that overlaps the output image.
    for shift_u in (-1.0, 0.0, 1.0):
        for shift_v in (-1.0, 0.0, 1.0):
            shifted = uv + np.array((shift_u, shift_v), dtype=np.float32)
            min_u, min_v = np.min(shifted, axis=0)
            max_u, max_v = np.max(shifted, axis=0)

            if max_u < 0.0 or min_u > 1.0 or max_v < 0.0 or min_v > 1.0:
                continue

            x0 = max(0, int(np.floor(min_u * width - 0.5)))
            x1 = min(width - 1, int(np.ceil(max_u * width - 0.5)))
            y0 = max(0, int(np.floor(min_v * height - 0.5)))
            y1 = min(height - 1, int(np.ceil(max_v * height - 0.5)))

            if x1 < x0 or y1 < y0:
                continue

            uv_a, uv_b, uv_c = shifted
            xs = (np.arange(x0, x1 + 1, dtype=np.float32) + 0.5) / width
            ys = (np.arange(y0, y1 + 1, dtype=np.float32) + 0.5) / height
            grid_x, grid_y = np.meshgrid(xs, ys)

            w1 = (
                (uv_b[1] - uv_c[1]) * (grid_x - uv_c[0]) +
                (uv_c[0] - uv_b[0]) * (grid_y - uv_c[1])
            ) / det
            w2 = (
                (uv_c[1] - uv_a[1]) * (grid_x - uv_c[0]) +
                (uv_a[0] - uv_c[0]) * (grid_y - uv_c[1])
            ) / det
            w3 = 1.0 - w1 - w2

            mask = (w1 >= -1e-6) & (w2 >= -1e-6) & (w3 >= -1e-6)
            if not np.any(mask):
                continue

            position = (
                w1[..., None] * positions[0] +
                w2[..., None] * positions[1] +
                w3[..., None] * positions[2]
            )
            normalized = np.clip((position / bounds) * 0.5 + 0.5, 0.0, 1.0)

            target = pixels[y0:y1 + 1, x0:x1 + 1, :3]
            target[mask] = normalized[mask]


def bake_sculpt_direct_to_buffer(obj, image, normalization_bounds):
    """Generate a Second Life-compatible sculpt map directly in memory.

    Sculpt maps are position maps: RGB encodes object-space X, Y, and Z.
    The implementation rasterizes evaluated mesh loop triangles into UV space
    using NumPy instead of testing every pixel against every polygon.

    Second Life's sculpted-prim system uses a maximum practical sculpt-map
    texture size of 128x128. The caller therefore must provide a square image
    no larger than 128x128.

    Args:
        obj: Mesh object used to generate the map.
        image: Target Blender image.
        normalization_bounds: Symmetric XYZ normalization extents.

    Raises:
        RuntimeError: If the mesh, UV map, image dimensions, or evaluated data
            are invalid.
    """
    width, height = image.size
    if width > 128 or height > 128:
        raise RuntimeError(
            f"Second Life sculpt maps must be no larger than 128x128; received {width}x{height}."
        )
    if width != height:
        raise RuntimeError(
            f"Second Life sculpt maps should be square; received {width}x{height}."
        )
    if obj.type != "MESH":
        raise RuntimeError(f"Sculpt maps require a mesh object; '{obj.name}' is {obj.type}.")

    depsgraph = bpy.context.evaluated_depsgraph_get()
    obj_eval = obj.evaluated_get(depsgraph)
    mesh_data = None

    try:
        mesh_data = obj_eval.to_mesh()
        if mesh_data is None:
            raise RuntimeError(f"Failed to evaluate mesh for object: {obj.name}")

        if not mesh_data.uv_layers.active:
            raise RuntimeError(f"Object '{obj.name}' has no active UV layer.")

        mesh_data.calc_loop_triangles()
        uv_layer = mesh_data.uv_layers.active

        vertices = np.empty((len(mesh_data.vertices), 3), dtype=np.float32)
        mesh_data.vertices.foreach_get("co", vertices.ravel())

        uv_data = np.empty((len(mesh_data.loops), 2), dtype=np.float32)
        uv_layer.data.foreach_get("uv", uv_data.ravel())

        pixels = np.empty((height, width, 4), dtype=np.float32)
        pixels[:, :, :3] = 0.5
        pixels[:, :, 3] = 1.0

        for triangle in mesh_data.loop_triangles:
            loop_indices = triangle.loops
            uv_triangle = uv_data[list(loop_indices)]
            vertex_indices = triangle.vertices
            positions = vertices[list(vertex_indices)]
            _rasterize_sculpt_triangle(
                pixels,
                width,
                height,
                uv_triangle,
                positions,
                np.asarray(normalization_bounds, dtype=np.float32),
            )

        image.pixels.foreach_set(pixels.ravel())
        image.update()

    except Exception as exc:
        raise RuntimeError(
            f"Sculpt map bake failed for object '{obj.name}': {exc}"
        ) from exc
    finally:
        if mesh_data is not None:
            obj_eval.to_mesh_clear()


def calculate_barycentric(px, py, uv1, uv2, uv3):
    """Compute barycentric coordinates for a UV-space point."""
    det = (
        (uv2.y - uv3.y) * (uv1.x - uv3.x) +
        (uv3.x - uv2.x) * (uv1.y - uv3.y)
    )
    if abs(det) < 1e-12:
        return -1.0, -1.0, -1.0

    w1 = (
        (uv2.y - uv3.y) * (px - uv3.x) +
        (uv3.x - uv2.x) * (py - uv3.y)
    ) / det
    w2 = (
        (uv3.y - uv1.y) * (px - uv3.x) +
        (uv1.x - uv3.x) * (py - uv3.y)
    ) / det
    return w1, w2, 1.0 - w1 - w2


def create_image_texture(
    material,
    name,
    width,
    height,
    alpha,
    float_buffer,
    interpolation,
    projection,
    extension,
    colorspace,
    file_format,
):
    """Create and activate an image texture node for baking.

    Returns:
        tuple: Created image texture node and image datablock.
    """
    image = bpy.data.images.new(
        name=name,
        width=width,
        height=height,
        alpha=alpha,
        float_buffer=float_buffer,
    )

    try:
        image.colorspace_settings.name = colorspace
    except (TypeError, ValueError) as exc:
        print(
            f"[Sequenced Bake] Could not set image color space '{colorspace}' "
            f"for '{image.name}': {exc}"
        )

    node_tree = material.node_tree
    node = node_tree.nodes.new("ShaderNodeTexImage")
    node.image = image
    node.interpolation = interpolation
    node.projection = projection.upper()
    node.extension = extension.upper()

    node_tree.nodes.active = node
    for existing in node_tree.nodes:
        existing.select = False
    node.select = True

    output = next(
        (item for item in node_tree.nodes if item.type == "OUTPUT_MATERIAL"),
        None,
    )
    if output:
        node.location = (output.location.x + 300, output.location.y)

    image.file_format = IMAGE_FORMAT_MAP.get(file_format, file_format)
    return node, image


def _configure_bake_pass(bake, bake_type, props):
    """Apply bake-pass-specific Cycles settings."""
    if bake_type == "DIFFUSE":
        bake.use_pass_direct = props.diffuse_lighting_direct
        bake.use_pass_indirect = props.diffuse_lighting_indirect
        bake.use_pass_color = props.diffuse_lighting_color
    elif bake_type == "GLOSSY":
        bake.use_pass_direct = props.glossy_lighting_direct
        bake.use_pass_indirect = props.glossy_lighting_indirect
        bake.use_pass_color = props.glossy_lighting_color
    elif bake_type == "TRANSMISSION":
        bake.use_pass_direct = props.transmission_lighting_direct
        bake.use_pass_indirect = props.transmission_lighting_indirect
        bake.use_pass_color = props.transmission_lighting_color
    elif bake_type == "COMBINED":
        bake.use_pass_direct = props.combined_lighting_direct
        bake.use_pass_indirect = props.combined_lighting_indirect
        bake.use_pass_diffuse = props.combined_contribution_diffuse
        bake.use_pass_glossy = props.combined_contribution_glossy
        bake.use_pass_transmission = props.combined_contribution_transmission
        bake.use_pass_emit = props.combined_contribution_emit
    elif bake_type == "NORMAL":
        bake.normal_space = props.normal_map_space
        bake.normal_r = props.normal_map_red_channel
        bake.normal_g = props.normal_map_green_channel
        bake.normal_b = props.normal_map_blue_channel


def _apply_color_management(scene, props):
    """Apply configured color-management values with console diagnostics."""
    assignments = (
        (scene.display_settings, "display_device", props.display_device),
        (scene.view_settings, "view_transform", props.view_transform),
        (scene.view_settings, "look", props.look),
    )
    for target, attribute, value in assignments:
        try:
            setattr(target, attribute, value)
        except (TypeError, ValueError, RuntimeError) as exc:
            print(f"[Sequenced Bake] Could not set {attribute}='{value}': {exc}")

    scene.view_settings.exposure = props.exposure
    scene.view_settings.gamma = props.gamma

    try:
        scene.sequencer_colorspace_settings.name = props.sequencer
    except (TypeError, ValueError, RuntimeError) as exc:
        print(f"[Sequenced Bake] Could not set sequencer color space '{props.sequencer}': {exc}")


def _save_image(image, output_dir, frame, file_format):
    """Save an image using its explicitly configured Blender file format."""
    os.makedirs(output_dir, exist_ok=True)
    blender_format = IMAGE_FORMAT_MAP.get(file_format, file_format)
    image.file_format = blender_format
    extension = file_format.lower()
    if extension in {"openexr", "exr"}:
        extension = "exr"
    filepath = os.path.join(output_dir, f"{frame}.{extension}")
    image.filepath_raw = filepath
    image.save()
    return filepath


def bake_frame(
    bake_type,
    props,
    frame,
    obj,
    mat,
    image_node,
    image,
    output_dir,
    sculpt_bounds=None,
):
    """Bake and save one frame for a material and bake pass."""
    scene = bpy.context.scene
    bake = scene.render.bake
    _configure_bake_pass(bake, bake_type, props)
    _apply_color_management(scene, props)

    cage_name = (
        props.selected_to_active_cage_object.name
        if props.selected_to_active_cage and props.selected_to_active_cage_object
        else ""
    )

    try:
        if bake_type == "SCULPT":
            if sculpt_bounds is None:
                raise RuntimeError("Sculpt normalization bounds were not calculated.")
            if image.size[0] > 128 or image.size[1] > 128:
                raise RuntimeError(
                    f"Second Life sculpt maps are limited to 128x128; "
                    f"requested {image.size[0]}x{image.size[1]}."
                )
            if image.size[0] != image.size[1]:
                raise RuntimeError("Second Life sculpt maps must use a square image.")

            bake_sculpt_direct_to_buffer(obj, image, sculpt_bounds)
            filepath = _save_image(
                image,
                output_dir,
                frame,
                props.sequenced_bake_image_format,
            )
        else:
            bpy.ops.object.bake(
                type="EMIT" if bake_type in {"METALLIC", "OCCLUSION"} else bake_type,
                use_selected_to_active=props.sequenced_selected_to_active,
                max_ray_distance=(
                    0.0 if props.selected_to_active_cage else props.selected_to_active_max_ray_distance
                ),
                cage_extrusion=props.selected_to_active_extrusion,
                cage_object=cage_name,
                use_cage=props.selected_to_active_cage,
            )
            filepath = _save_image(
                image,
                output_dir,
                frame,
                props.sequenced_bake_image_format,
            )

        print(f"[Sequenced Bake] Saved {bake_type} frame {frame}: {filepath}")
        return filepath
    except Exception as exc:
        print(
            f"[Sequenced Bake] Bake failed - material='{mat.name}', "
            f"type='{bake_type}', frame={frame}: {exc}"
        )
        raise
