schema_version = "1.0.0"
id = "sequenced_bake"
name = "Sequenced Bake"
version = "1.0.0"
tagline = "Baking toolset for baking material sequences."
maintainer = "Anthony O'Connell"
type = "add-on"
tags = ["3D View", "Material", "Bake"]
blender_version_min =  "4.1.0"
license = ["SPDX:GPL-2.0-or-later"]
copyright = ["2024 Anthony O'Connell"]
website = "https://github.com/PurgatoryMP/SpriteSheetCreator"
